name: Publish Bottles
concurrency:
  group: ${{ github.ref }}
  max: 2

on:
  push:
    branches:
      - main

jobs:
  publish-bottles:
    runs-on: macos-latest
    env:
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build Bottles
        run: brew install --build-bottle ./Formula/kinetik-cli.rb && brew bottle ./Formula/kinetik-cli.rb

      - name: Upload Bottles
        uses: actions/upload-artifact@v2
        with:
          name: kinetik-cli
          path: kinetik-cli--0.13.5.monterey.bottle.1.tar.gz

      - name: Publish Bottles
        uses: Homebrew/actions/publish-formula@main
        with:
          formula: ./Formula/kinetik-cli.rb
          tag: v2.0.0
          bottles: kinetik-cli--0.13.5.monterey.bottle.1.tar.gz
