name: create bottle
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
#    branches:
#      - feature
  pull_request:
jobs:
  anne-try:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master
      - name: setup git/install kinetik/create bottle
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.email "engineering@section6.nz"
          git config --global user.name "Anne Wang"
          ls -R
          pwd
          brew tap xiaoanne/kinetik-cli
          brew install --build-bottle kinetik-cli
          brew bottle kinetik-cli
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bottle-tarball
          path: /Users/runner/work/homebrew-kinetik-cli/homebrew-kinetik-cli/bottle/kinetik-cli--0.13.5.arm64_monterey.bottle.1.tar.gz

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bottle-tarball
          path: ./bottle

#      - run: |
#          cd bottle
#          tar -zxvf kinetik-cli--0.13.5.monterey.bottle.1.tar.gz -C .
#          ls -R

      - name: Publish Bottle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          ls -R
          cd bottle
          brew pr-upload --verbose --keep-old --root-url="https://ghcr.io/v2/xiaoanne/kinetik-cli"
