name: brew test-bot
on:
  push:
#  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
#        os: [ubuntu-22.04, macos-12]
        os: [macos-12]
#    runs-on: ${{ matrix.os }}
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Create bottle file
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT }}
        run: |
          brew install --build-bottle Formula/kinetik-cli.rb
          kinetik
          brew bottle Formula/kinetik-cli.rb
          ls -R
#          ls kinetik-cli--0.13.5.monterey.bottle.1.tar.gz

      - name: Upload bottles as artifact
#        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: kinetik-cli--0.13.5.monterey.bottle.1.tar.gz
