name: create bottle
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
#    branches:
#      - feature
  pull_request:
jobs:
  anne-try:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master
      - name: install kinetik/create bottle
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT }}
        run: |
          ls -R
          pwd
          brew tap xiaoanne/kinetik-cli
          brew install --build-bottle kinetik-cli
          brew bottle kinetik-cli
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bottle-tarball
          path: |
            /home/runner/work/homebrew-kinetik-cli/homebrew-kinetik-cli/bottle/kinetik-cli--0.13.5.arm64_monterey.bottle.1.tar.gz
            /home/runner/work/homebrew-kinetik-cli/homebrew-kinetik-cli/kinetik-cli--0.13.5.x86_64_linux.bottle.1.tar.gz

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bottle-tarball
          path: ./bottle

      - name: Publish Bottle
        env:
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{secrets.PAT}}
        run: |
          git config --global user.email "anne@example.com"
          git config --global user.name "anne"
          cd bottle
          ls -R /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/xiaoanne/
          brew pr-upload --verbose --root-url="https://ghcr.io/v2/xiaoanne/kinetik-cli"
