name: brew test-bot
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master
      - name: setup git/install kinetik/create bottle
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.email "engineering@section6.nz"
          git config --global user.name "Anne Wang"
          ls -R
          pwd
          brew tap xiaoanne/kinetik-cli
          brew install --build-bottle kinetik-cli
          brew bottle kinetik-cli
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kinetik binaries
          path: /Users/runner/work/homebrew-kinetik-cli/homebrew-kinetik-cli/kinetik-cli--0.13.5.monterey.bottle.1.tar.gz

      - name: Publish Bottle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EDITOR: vi
        run: |
          hub release create v1.0.0
          hub release upload v1.0.0 /Users/runner/work/homebrew-kinetik-cli/homebrew-kinetik-cli/kinetik-cli--0.13.5.monterey.bottle.1.tar.gz
