name: create bottle
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
#    branches:
#      - feature
  pull_request:
jobs:
  anne-try:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
#    runs-on: ubuntu-latest
#    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master
      - name: install kinetik/create bottle
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT }}
        run: |
          ls -R
          pwd
          brew tap xiaoanne/kinetik-cli
          brew install --build-bottle kinetik-cli
          brew bottle kinetik-cli --json
          # brew test-bot --only-formulae --root-url=https://ghcr.io/v2/xiaoanne/kinetik-cli
          # brew test-bot --tap=xiaoanne/kinetik-cli --root-url=https://ghcr.io/v2/xiaoanne/kinetik-cli xiaoanne/kinetik-cli/kinetik-cli
          # brew test-bot --only-formulae xiaoanne/kinetik-cli/kinetik-cli
          ls -R
          cp ./kinetik-* ./bottle
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bottle-tarball
          path: |
            ./bottle/*.txt
            ./bottle/*.gz

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bottle-tarball
          path: ./bottle

      - name: Publish Bottle
        env:
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{secrets.PAT}}
        run: |
          git config --global user.email "anne@example.com"
          git config --global user.name "anne"
          cd bottle
          ls -R /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/xiaoanne/
          brew pr-upload --verbose --root-url="https://ghcr.io/v2/xiaoanne/kinetik-cli"
