name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: run
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT }}
        run: |
          ls -R
          pwd
          brew tap xiaoanne/kinetik-cli
          brew install --build-bottle kinetik-cli
          brew bottle kinetik-cli
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kinetik binaries
          path: /Users/runner/work/homebrew-kinetik-cli/homebrew-kinetik-cli/kinetik-cli--0.13.5.monterey.bottle.1.tar.gz

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: /Users/runner/work/homebrew-kinetik-cli/homebrew-kinetik-cli/kinetik-cli--0.13.5.monterey.bottle.1.tar.gz

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
#          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: brew pr-pull --debug --tap=$GITHUB_REPOSITORY