name: brew test-bot
on:
  push:
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Create bottle file
        run: |
          brew test-bot --only-formulae --root-url=https://ghcr.io/v2/xiaoanne/kinetik-cli Formula/kinetik-cli.rb
          ls -R
          ls kinetik-cli--0.13.5.monterey.bottle.1.tar.gz

      - name: Upload bottles as artifact
#        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: kinetik-cli--0.13.5.monterey.bottle.1.tar.gz
