name: brew test-bot
on:
  push:
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
#      - name: Set up Homebrew
#        id: set-up-homebrew
#        uses: Homebrew/actions/setup-homebrew@master

      - name: List workspace files
        run: |
          ls -R
          ls kinetik-cli--0.13.5.monterey.bottle.1.tar.gz

      - name: Upload bottles as artifact
#        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: kinetik-cli--0.13.5.monterey.bottle.1.tar.gz
